name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project (Skip Tests)
        run: mvn -B clean install -DskipTests

      - name: Run Unit Tests
        run: mvn -B test -Dtest=*Test

      - name: Run Integration Tests
        run: mvn -B verify -DskipUnitTests=true
